# Generated by Django 5.2.13 on 2026-04-21 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='especialidad',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='carnet_identidad',
            new_name='codigo_unico',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='apellido_materno',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='apellido_paterno',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='codigo_usuario',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='fecha_baja',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='foto_perfil',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='matricula_profesional',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='segundo_nombre',
        ),
        migrations.DeleteModel(
            name='Speciality',
        ),
    ]
