# Generated by Django 5.2.13 on 2026-04-21 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='unique_code',
            new_name='codigo_unico',
        ),
    ]
