# Generated by Django 5.2.13 on 2026-05-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_remove_customuser_especialidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalequipment',
            name='caracteristicas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='certificaciones',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='condiciones_uso',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='dimensiones',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='fecha_adquisicion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='frecuencia_mantenimiento',
            field=models.IntegerField(blank=True, help_text='En dias', null=True),
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='historial',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='mantenimiento_correctivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='mantenimiento_predictivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='mantenimiento_preventivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='materiales',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='peso',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='proveedor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='proximo_mantenimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='requisitos_energia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='vida_util',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicalequipment',
            name='codigo_interno',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='medicalequipment',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
