# Generated by Django 5.2.13 on 2026-05-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_medicalequipment_caracteristicas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalequipment',
            name='analisis_ia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='ruta_modelo_3d',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='salud_equipo',
            field=models.IntegerField(blank=True, help_text='0-100', null=True),
        ),
    ]
