# Generated by Django 5.2.13 on 2026-05-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0005_customuser_birth_date_customuser_cellphone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalequipment',
            name='falla_activa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='falla_coordenada_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='falla_coordenada_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='falla_coordenada_z',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='falla_descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
