# Generated by Django 5.2.13 on 2026-05-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0006_medicalequipment_falla_activa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalequipment',
            name='analisis_ia',
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='mantenimientos_previos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
