# Generated by Django 5.2.13 on 2026-05-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0007_remove_medicalequipment_analisis_ia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='bitacoras_ingeniero',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
