# Generated by Django 5.2.13 on 2026-05-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0008_workorder_bitacoras_ingeniero'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permisos',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
