# Generated by Django 5.2.13 on 2026-05-19 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0009_role_permisos'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Ocupado', 'Ocupado'), ('Fuera de Unidad', 'Fuera de Unidad')], default='Disponible', max_length=50)),
                ('ubicacion_actual', models.CharField(blank=True, max_length=100, null=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('ingeniero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problema_visible', models.CharField(max_length=200)),
                ('prioridad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta'), ('Critica', 'Crítica')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Pendiente de Inspeccion', 'Pendiente de Inspección'), ('Inspeccionado', 'Inspeccionado'), ('Orden Generada', 'Orden Generada'), ('Rechazado', 'Rechazado')], default='Pendiente de Inspeccion', max_length=50)),
                ('reporte_preliminar_ingeniero', models.TextField(blank=True, null=True)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('fecha_inspeccion', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidentes_reportados', to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidentes', to='infrastructure.medicalequipment')),
                ('ingeniero_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_asignados', to=settings.AUTH_USER_MODEL)),
                ('orden_trabajo_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidente_origen', to='infrastructure.workorder')),
            ],
        ),
    ]
