# Generated by Django 5.2.13 on 2026-05-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0010_engineeravailability_incidentreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='enlace_destino',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='enlace_destino',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='engineeravailability',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Ocupado', 'Ocupado'), ('Fuera de Unidad', 'Fuera de Unidad'), ('Desconectado', 'Desconectado')], default='Disponible', max_length=50),
        ),
    ]
