# Generated by Django 5.2.13 on 2026-06-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0011_auditlog_enlace_destino_notification_enlace_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalequipment',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='equipments/'),
        ),
    ]
